### ISSUE TITLE
Cant get Loading indicator on old version of flutter showing this message on flutter 2.10 (flutter 3.0 released already)

### ISSUE THREAD

**Issue by Ujjawalmaurya** [TinoGuo/loading_indicator#32]
[example-project]flutter pub get
╔════════════════════════════════════════════════════════════════════════════╗
║ A new version of Flutter is available!                                                                                                                                          
║                                                                                                                                                                                                     
║ To update to the latest version, run "flutter upgrade".                                                                                                               
╚════════════════════════════════════════════════════════════════════════════╝

Running "flutter pub get" in example-project...                         
Because every version of flutter_test from sdk depends on collection 1.15.0 and loading_indicator >=3.0.4 depends on collection ^1.16.0, flutter_test from sdk is incompatible with loading_indicator >=3.0.4.
So, because pos depends on both loading_indicator ^3.1.0 and flutter_test from sdk, version solving failed.
pub get failed (1; So, because pos depends on both loading_indicator ^3.1.0 and flutter_test from sdk, version solving failed.)
exit code 1

**Comment by TinoGuo** [comment]
@Ujjawalmaurya  can u share the example-project? I created example project, everything looks fine

**Comment by TinoGuo** [comment]
close issue due to no response

**Comment by Ujjawalmaurya** [comment]
That issue is resolved in their further updates. That new version package was not functioning in flutter 2.10 after 3.0 was released. Now its working perfectly fine.
