### ISSUE TITLE
Set Secondary Color on Loading Indicator

### ISSUE THREAD

**Issue by Lone-Wolf17** [TinoGuo/loading_indicator#5]
Please How can I set the secondary color on each Loading indicator? Thank you

**Comment by TinoGuo** [comment]
Hi, @Lone-Wolf17 , I don't get the `secondary color`, can u elaborate it?

**Comment by Lone-Wolf17** [comment]
Hello @TinoGuo , So let's say i am using animation type 24 (lineSpinFadeLoader). To give the loading effect. the shapes have two different states, when they are brightened and the other when they are kind of smaller / dull. I can set the color of the loader, but I cannot set the color to be used when that shape is not active. Like a background color, if I set color to be blue and the secondary color/background color to grey, the non-active balls are grey and the active balls are blue.

God, I hope you understand what I am trying to say.

**Comment by TinoGuo** [comment]
correct me if I was wrong, your requirement is to define the active state, disabled or other state, in every state respectively shows different color.

**Comment by Lone-Wolf17** [comment]
Actually no, I meant some thing like in Flutter's  CircularProgressIndicator or LinearProgressIndicator Where you can set the backgroundColor like this 
 `LinearProgressIndicator (
     backgroundColor: Colors.grey
 );`

![Screenshot (26)](https://user-images.githubusercontent.com/53178226/100740543-311f8080-33d9-11eb-90fb-02a2ccaf61b9.png)

**Comment by TinoGuo** [comment]
I see, good point, but now the lib not able to provide yet. welcome to PR!

**Comment by TinoGuo** [comment]
support from 3.0.0
