### ISSUE TITLE
Migrate to sound null safety

### ISSUE THREAD

**Issue by LearningRaph** [TinoGuo/loading_indicator#8]
Migrate to sound null safety
Bump up package version

**Comment by Mayb3Nots** [comment]
I have spent hours migrating this package here #9 . Hopefully, the owner sees it and checks it out.

**Comment by LearningRaph** [comment]
If he doesn't we found a solution with others. You can make a master branch of your own with the PR and then get it in your config file like this :

flutter_icons:
  git:
    url: https://github.com/adarsh-technocrat/flutter-icons

Leave him a few days and if he doesn't answer we can do that :)

**Comment by Mayb3Nots** [comment]
> If he doesn't we found a solution with others. You can make a master branch of your own with the PR and then get it in your config file like this :
> 
> flutter_icons:
> git:
> url: https://github.com/adarsh-technocrat/flutter-icons
> 
> Leave him a few days and if he doesn't answer we can do that :)

Yup you can use my forked version while the owner havent merge yet.
`loading_indicator: 
  git:
  url: `https://github.com/Mayb3Nots/loading_indicator
  ref: master'
